---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    # Example "dudecalledbro/molecule-rockylinux-9:latest"
    image: "${NAMESPACE:-dudecalledbro}/${IMAGE:-molecule-rockylinux-9}:${TAG:-latest}"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
